apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-scrape-config
  labels:
    name: cluster-scrape-config
  namespace: flashcat
data:
  cluster-scrape.yaml: |-
    global: 
      scrape_interval: 15s 
    scrape_configs:
      - job_name: 'demo-java-jmx'
        kubernetes_sd_configs:
          - role: endpoints
        relabel_configs:
          - source_labels: [__meta_kubernetes_namespace, __meta_kubernetes_service_name, __meta_kubernetes_endpoint_port_name]
            action: keep
            regex: flashcat;demo-java-service;jmx

          - source_labels: [__meta_kubernetes_namespace]
            target_label: "namespace"  # 添加 namespace 标签
            replacement: "$1"          # 直接继承原始值
          - source_labels: [__meta_kubernetes_pod_name]
            target_label: "pod"        # 添加 pod 名称标签
          - source_labels: [__meta_kubernetes_pod_container_name]
            target_label: "container"  # 添加容器名称标签 
          - source_labels: [ "pod" ]
            regex : "(.*)-[a-zA-Z0-9]{5,10}-[a-zA-Z0-9]{5}"
            target_label : "deployment"
            replacement : "${1}"          
    remote_write:
      - url: 'http://10.201.0.207:19000/prometheus/v1/write'
