apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-java-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-java
  template:
    metadata:
      labels:
        app: demo-java
    spec:
      containers:
      - name: demo-java
        image: flashcat.tencentcloudcr.com/public/java-demo
        ports:
        - containerPort: 8080
          name: http
        - containerPort: 9080
          name: jmx
        resources:
          requests:
            memory: "1Gi"
            cpu: "1"
          limits:
            memory: "1Gi"
            cpu: "1"
---
apiVersion: v1
kind: Service
metadata:
  name: demo-java-service
spec:
  selector:
    app: demo-java
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    name: http
  - protocol: TCP
    port: 9080
    targetPort: 9080
    name: jmx
  type: ClusterIP
