apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-java-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-java
  template:
    metadata:
      annotations:
        # 表示该pod日志需要采集
        categraf/logs.stdout.collect: "true"
        # 表示该pod日志需要使用哪个Kafka Topic（建议，具有相同日志格式的服务，使用一个topic；如果想不同服务区分不通的Topic，可以将基于namespace+deployment_name（有规范的命名规则）创建 topic name,便于后端的自动处理）
        categraf/logs.stdout.topic: "kubernetes-demo-java" 
        #表示日志中会将label和annotaion中以xx为前缀的标签附加到日志tag中,空标识所有标签
        categraf/tags.prefix: "" 
      labels:
        app: demo-java
    spec:
      containers:
      - name: demo-java
        image: flashcat.tencentcloudcr.com/public/java-demo
        ports:
        - containerPort: 8080
          name: http
        - containerPort: 9080
          name: jmx
        resources:
          requests:
            memory: "1Gi"
            cpu: "1"
          limits:
            memory: "1Gi"
            cpu: "1"
---
apiVersion: v1
kind: Service
metadata:
  name: demo-java-service
spec:
  selector:
    app: demo-java
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    name: http
  - protocol: TCP
    port: 9080
    targetPort: 9080
    name: jmx
  type: ClusterIP

